portage: Add LUET_PORTAGE_IGNORE_TAR_WARNING

diff --git a/extensions/portage/luet-portage b/extensions/portage/luet-portage
--- a/extensions/portage/luet-portage
+++ b/extensions/portage/luet-portage
@@ -13,6 +13,7 @@ LUET_PORTAGE_PKGMETA=${LUET_PORTAGE_PKGMETA:-0}
 LUET_PORTAGE_TMPDIR=${LUET_PORTAGE_TMPDIR:-/luet-extract}
 LUET_PORTAGE_CACHE_PACKAGES=${LUET_PORTAGE_CACHE_PACKAGES:-/var/cache/portage/packages}
 LUET_PORTAGE_QUICKPKG_OPTS=${LUET_PORTAGE_QUICKPKG_OPTS:---include-config=y}
+LUET_PORTAGE_IGNORE_TAR_WARNING=${LUET_PORTAGE_IGNORE_TAR_WARNING:-0}
 
 summary () {
   echo "luet-portage params:
@@ -65,7 +66,17 @@ extract_pkg_files () {
   ls -l ${LUET_PORTAGE_TMPDIR}
 
   tar xvjf ${LUET_PORTAGE_TMPDIR}/${name}-${version}${vsuffix}.tar.bz2 \
-    -C ${LUET_PORTAGE_TARGETDIR} || return 1
+    -C ${LUET_PORTAGE_TARGETDIR} || {
+    # If we use multiple packages in the same target dir
+    # you can receive error on create directories/symlink.
+    # Example: sys-libs/glibc
+    # tar: ./lib: Cannot create symlink to 'lib64': File exists
+    if [ "${LUET_PORTAGE_IGNORE_TAR_WARNING}" != "1" ] ; then
+      return 1
+    else
+      echo "[${pkg}] Ignoring tarball warning/errors."
+    fi
+  }
 
   return 0
 }
