Stop when job fails in smart-build

diff --git a/extensions/k8s-build-scheduler/luet-k8s-build-scheduler b/extensions/k8s-build-scheduler/luet-k8s-build-scheduler
--- a/extensions/k8s-build-scheduler/luet-k8s-build-scheduler
+++ b/extensions/k8s-build-scheduler/luet-k8s-build-scheduler
@@ -267,7 +267,12 @@ EOF
             do
                 echo "Package $PACKAGE_CATEGORY/$PACKAGE_NAME @ $PACKAGE_VERSION not built yet, sleeping"
                 kubectl logs -f -c spec-build -n $NAMESPACE $JOB_NAME
-                sleep 5
+
+                JOB_STATE=$(kubectl get packagebuild -n $NAMESPACE $JOB_NAME -o json | jq -r '.status.state')
+                if [[ "$JOB_STATE" == "Failed" ]]; then
+                    echo "Job failed, exiting"
+                    exit 1
+                fi
             done
 
             echo "Package $PACKAGE_CATEGORY/$PACKAGE_NAME @ $PACKAGE_VERSION built!"
